/**
 * @file adnewuserdialog.h
 * @author CalaW (maker_cc@foxmail.com)
 * @brief Dialog for admin user to add new user
 * 
 * auto generated by qt wizard
 * 
 * @version 0.1
 * @date 2021-08-07
 * 
 */

#ifndef ADNEWUSERDIALOG_H
#define ADNEWUSERDIALOG_H

#include <QDialog>
#include <QString>

namespace Ui {
class adNewUserDialog;
}

class adNewUserDialog : public QDialog
{
    Q_OBJECT

public:
    explicit adNewUserDialog(QWidget *parent = nullptr);
    ~adNewUserDialog();

signals:
    void adAddUserConfirm(const QString& name, const QString& pwd); //send data to main window
    void adDelUserConfirm(const QString& name);
    void adChUserPwdConfirm(const QString& name, const QString& pwd); //send data to main window

private slots:

    void on_buttonBox_accepted();

    void on_methodChk_currentIndexChanged(int index);

private:
    Ui::adNewUserDialog *ui;
};

#endif // ADNEWUSERDIALOG_H
