/**
 * @file logindialog.h
 * @author CalaW (maker_cc@foxmail.com)
 * @brief login window
 * @version 0.1
 * @date 2021-08-07
 * 
 * auto generated by qt
 */
#ifndef LOGINDIALOG_H
#define LOGINDIALOG_H

#include <QDialog>
#include "logincontroller.h"

namespace Ui {
class LoginDialog;
}

class LoginDialog : public QDialog
{
    Q_OBJECT

public:
    explicit LoginDialog(QWidget *parent = nullptr);
    ~LoginDialog();
    User* getLoginUserPtr();

signals:
    void loginSuccess(const LoginController&);

private slots:
    void on_LoginButton_clicked();
    void showLoginDialog();

private:
    Ui::LoginDialog *ui;
    LoginController login_ctrl;
};

#endif // LOGINDIALOG_H
